---
# tasks file for roles/joining-masters
- name: Copy join command from Ansiblehost to the other master nodes.
  become: yes
  copy:
    src: "/tmp/master_join_command-{{ region }}"
    dest: /tmp/master_join_command
    mode: 0777

- name: Join other master nodes to the cluster.
  become: yes
  command: sh /tmp/master_join_command
  register: joined_or_not

- name: create .kube directory
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copies admin.conf to user's kube config
  become: yes
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
