---
# tasks file for roles/otherdb
- name: "Install ansible python3 mysql dependency"
  become: yes
  apt:
    name: python3-mysqldb
    state: latest
    
- name: Copy galera.cnf file
  become: yes
  template:
    src: galera.j2
    dest: /etc/mysql/mariadb.conf.d/galera.cnf

- name: Stop mariaDB
  become: yes
  ansible.builtin.systemd:
    name: mariadb
    state: stopped
