- name: Db status
  hosts: dbs
  tasks:
    - name: Get galera cluster node status
      become: yes
      community.mysql.mysql_query:
        login_db: testDBB
        query: SHOW GLOBAL STATUS LIKE 'wsrep_local_state_comment'
      register: node_status
    - debug:
        msg: "{{ node_status }}"
