---
# vars file for roles/ns-config
key_usa: "YWJjZGVmZw=="
key_asia: "aGlqa2xtbg=="
key_default: "b3BxcnN0dQ=="
master_ip: "34.88.47.71"
slave_ip: "35.228.71.77"
domain: "group2finalproject.ml"
asia_ip: "34.149.54.177"
usa_ip: "35.227.211.154"
txt: "s9BjdploFcP4I7RWbtt86sWwc1gH1YdaaRF7MpEfI9w"
