# Generated by Django 3.2.5 on 2021-12-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('AssetID', models.IntegerField()),
                ('Owner', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Criticality', models.CharField(choices=[('C', 'Critical'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
            ],
            options={
                'unique_together': {('Name', 'AssetID', 'Owner', 'Description', 'Location', 'Criticality')},
            },
        ),
    ]
