# Generated by Django 3.2.5 on 2021-12-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='AssetID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
